### ISSUE TITLE
Getting blank sentences after model training

### ISSUE THREAD

**Issue by Kushpatel49** [Aakash12980/Sentence-Simplification-using-BERT-GPT2#1]
Het Aakash, I've been going through your code and tried to setup on my computer. After training, the sentences are not getting encoded and storing as a blank white spaces.....Can you please help or provide your model?

**Comment by Aakash12980** [comment]
Hey @Kushpatel49 unfortunately I dont have the trained model as the model was saved on my college's drive and it has been terminated way before. I would suggest training model to 4 to 6 epoch only with 4 batch size. Hope that works for you. Also, the project might be using outdated package. If you can enhance the current project feel free to send me a pull request.
